# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables will be set in the Netlify UI
# Make sure you've added VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY there
